services:

  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html

  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html


  #postgresql
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: diary_db
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  #adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
