services:

  #nginx
  web:
    restart: always
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"

  #php
  app:
    restart: always
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app/public:/var/www/html/public


  #postgresql
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: diary_db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  #adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
